SELECT
    TO_CHAR(DATE_SUBMITTED_ID, 'YYYY') AS review_year,
    ROUND(AVG(SEAT_COMFORT), 2) AS avg_seat_comfort,
    ROUND(AVG(FOOD_AND_BEVERAGES), 2) AS avg_food,
    ROUND(AVG(INFLIGHT_ENTERTAINMENT), 2) AS avg_entertainment
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
GROUP BY TO_CHAR(DATE_SUBMITTED_ID, 'YYYY')
ORDER BY review_year;