SELECT
  TO_CHAR(DATE_SUBMITTED_ID, 'YYYY') AS review_year,
  COUNT(*) AS total_reviews,
  SUM(CASE WHEN RECOMMENDED = TRUE THEN 1 ELSE 0 END) / COUNT(*) AS pct_recommended
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
GROUP BY TO_CHAR(DATE_SUBMITTED_ID, 'YYYY')
ORDER BY review_year;
