SELECT
  TO_CHAR(DATE_SUBMITTED_ID, 'YYYY') AS review_year,
  ROUND(AVG(AVERAGE_RATING), 2) AS avg_rating,
  ROUND(AVG(VALUE_FOR_MONEY), 2) AS avg_value_for_money
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
GROUP BY TO_CHAR(DATE_SUBMITTED_ID, 'YYYY')
ORDER BY review_year;