SELECT s2.AIRCRAFT_ID, 
    s2.AIRCRAFT_MANUFACTURER, 
    s2.AIRCRAFT_MODEL, 
    s2.SEAT_CAPACITY, 
    s1.REVIEW_ID
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED AS s1
JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_AIRCRAFT s2
ON s1.AIRCRAFT_ID = s2.AIRCRAFT_ID
HAVING s1.AIRLINE = 'United Airlines';