SELECT 
    t1.DESTINATION_LOCATION_ID destination, 
    t2.LOCATION_ID locationid, 
    t2.CITY city, 
    t2.AIRPORT airport
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED t1
JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_LOCATION t2
ON t1.DESTINATION_LOCATION_ID = t2.LOCATION_ID
HAVING t1.AIRLINE = 'United Airlines';



