SELECT
  AVG(AVERAGE_RATING) AS "AVG Rating",
  lo.CITY AS "Origin City",
  ld.CITY AS "Destination City",
  COUNT(*) AS "Count"
FROM
  SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED r
  JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_LOCATION lo ON r.ORIGIN_LOCATION_ID = lo.LOCATION_ID
  JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_LOCATION ld ON r.DESTINATION_LOCATION_ID = ld.LOCATION_ID
WHERE
  lo.CITY IN ( SELECT l.CITY
    FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED r
    JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_LOCATION l ON r.ORIGIN_LOCATION_ID = l.LOCATION_ID
    GROUP BY l.CITY
    ORDER BY COUNT(*) DESC
    LIMIT 6)
  AND ld.CITY IN (SELECT l.CITY
    FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED r
    JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_LOCATION l ON r.DESTINATION_LOCATION_ID = l.LOCATION_ID
    GROUP BY l.CITY
    ORDER BY COUNT(*) DESC
    LIMIT 6)
GROUP BY lo.CITY, ld.CITY
ORDER BY COUNT(*) DESC
LIMIT 6;
