SELECT
  ROUND(AVG(AVERAGE_RATING), 2) AS avg_rating,
  COUNT(*) AS total_reviews,
  AVG(CASE WHEN RECOMMENDED = TRUE THEN 1 ELSE 0 END) AS pct_recommended,
  ROUND(AVG(CASE WHEN VERIFIED = TRUE THEN 1 ELSE 0 END), 2) AS pct_verified
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines';