SELECT 
    c.NATIONALITY, 
    COUNT(*) AS total_reviews
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED f
JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_CUSTOMER c
  ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE f.AIRLINE = 'United Airlines'
GROUP BY c.NATIONALITY
ORDER BY total_reviews DESC
LIMIT 5;