SELECT 
    SEAT_TYPE,
    COUNT(*) AS review_count
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines' and SEAT_TYPE IS NOT NULL 
GROUP BY SEAT_TYPE
ORDER BY review_count DESC;
